<|ref|>text<|/ref|><|det|>[[133, 86, 487, 113]]<|/det|>
Foundation for Autonomous Agents and Multiagent Systems.

<|ref|>text<|/ref|><|det|>[[116, 126, 488, 206]]<|/det|>
Priyanshu Kumar, Elaine Lau, Saranya Vijayakumar, Tu Trinh, Elaine T Chang, Vaughn Robinson, Shuyan Zhou, Matt Fredrikson, Sean M. Hendryx, Summer Yue, and Zifan Wang. 2025. Aligned LLMs are not aligned browser agents. In The Thirteenth International Conference on Learning Representations.

<|ref|>text<|/ref|><|det|>[[116, 218, 488, 311]]<|/det|>
Christine P. Lee, David Porfirio, Xinyu Jessica Wang, Kevin Chenkai Zhao, and Bilge Mutlu. 2025a. Veriplan: Integrating formal verification and llms into end-user planning. In Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems, CHI '25, New York, NY, USA. Association for Computing Machinery.

<|ref|>text<|/ref|><|det|>[[116, 324, 488, 364]]<|/det|>
Donghyun Lee and Mo Tiwari. 2024. Prompt infection: Llm-to-llm prompt injection within multi-agent systems. Preprint, arXiv:2410.07283.

<|ref|>text<|/ref|><|det|>[[116, 377, 488, 430]]<|/det|>
Hwiwon Lee, Ziqi Zhang, Hanxiao Lu, and Lingming Zhang. 2025b. Sec-bench: Automated benchmarking of llm agents on real-world software security tasks. Preprint, arXiv:2506.11791.

<|ref|>text<|/ref|><|det|>[[116, 443, 488, 509]]<|/det|>
Ido Levy, Ben Wiesel, Sami Marreed, Alon Oved, Avi Yaeli, and Segev Shlomov. 2025. STWebAgentBench: A benchmark for evaluating safety & trustworthiness in web agents. In ArXiv. ArXiv:2410.06703.

<|ref|>text<|/ref|><|det|>[[116, 523, 488, 576]]<|/det|>
Ang Li, Yin Zhou, Vethavikasthini Chithrra Raghuram, Tom Goldstein, and Micah Goldblum. 2025a. Commercial llm agents are already vulnerable to simple yet dangerous attacks. Preprint, arXiv:2502.08586.

<|ref|>text<|/ref|><|det|>[[116, 589, 488, 643]]<|/det|>
Evan Li, Tushin Mallick, Evan Rose, William Robertson, Alina Oprea, and Cristina Nita-Rotaru. 2025b. Ace: A security architecture for llm-integrated app systems. Preprint, arXiv:2504.20984.

<|ref|>text<|/ref|><|det|>[[116, 656, 488, 735]]<|/det|>
Simin Li, Jun Guo, Jingqiao Xiu, Ruixiao Xu, Xin Yu, Jiakai Wang, Aishan Liu, Yaodong Yang, and Xianglong Liu. 2024. Byzantine robust cooperative multi-agent reinforcement learning as a bayesian game. In The Twelfth International Conference on Learning Representations.

<|ref|>text<|/ref|><|det|>[[116, 748, 488, 853]]<|/det|>
Weizhen Li, Jianbo Lin, Zhuosong Jiang, Jingyi Cao, Xinpeng Liu, Jiayu Zhang, Zhenqiang Huang, Qianben Chen, Weichen Sun, Qiexiang Wang, Hongxuan Lu, Tianrui Qin, Chenghao Zhu, Yi Yao, Shuying Fan, Xiaowan Li, Tiannan Wang, Pai Liu, King Zhu, and 11 others. 2025c. Chain-of-agents: End-to-end agent foundation models via multi-agent distillation and agentic rl. Preprint, arXiv:2508.13167.

<|ref|>text<|/ref|><|det|>[[116, 866, 488, 919]]<|/det|>
Wenhao Li, Selvakumar Manickam, Yung wey Chong, and Shankar Karuppayah. 2025d. Phishdebate: An llm-based multi-agent framework for phishing website detection. Preprint, arXiv:2506.15656.

<|ref|>text<|/ref|><|det|>[[510, 85, 884, 140]]<|/det|>
Ziyang Li, Saikat Dutta, and Mayur Naik. 2025e. IRIS: LLM-assisted static analysis for detecting security vulnerabilities. In The Thirteenth International Conference on Learning Representations.

<|ref|>text<|/ref|><|det|>[[510, 147, 884, 200]]<|/det|>
Liang Lin, Zhihao Xu, Xuehai Tang, Shi Liu, Biyu Zhou, Fuqing Zhu, Jizhong Han, and Songlin Hu. 2025a. Paper summary attack: Jailbreaking llms through llm safety papers. Preprint, arXiv:2507.13474.

<|ref|>text<|/ref|><|det|>[[510, 208, 884, 274]]<|/det|>
Xihuan Lin, Jie Zhang, Gelei Deng, Tianzhe Liu, Xiaolong Liu, Changcai Yang, Tianwei Zhang, Qing Guo, and Riqing Chen. 2025b. Ircopilot: Automated incident response with large language models. Preprint, arXiv:2505.20945.

<|ref|>text<|/ref|><|det|>[[510, 282, 884, 375]]<|/det|>
Fengyu Liu, Yuan Zhang, Jiaqi Luo, Jiarun Dai, Tian Chen, Letian Yuan, Zhengmin Yu, Youkun Shi, Ke Li, Chengyuan Zhou, Hao Chen, and Min Yang. 2025a. Make agent defeat agent: automatic detection of taint-style vulnerabilities in llm-based agents. In Proceedings of the 34th USENIX Conference on Security Symposium, SEC '25, USA. USENIX Association.

<|ref|>text<|/ref|><|det|>[[510, 382, 884, 449]]<|/det|>
Xiaogeng Liu, Nan Xu, Muhao Chen, and Chaowei Xiao. 2024a. AutoDAN: Generating stealthy jailbreak prompts on aligned large language models. In The Twelfth International Conference on Learning Representations.

<|ref|>text<|/ref|><|det|>[[510, 456, 884, 523]]<|/det|>
Yi Liu, Gelei Deng, Yuekang Li, Kailong Wang, Zihao Wang, Xiaofeng Wang, Tianwei Zhang, Yepang Liu, Haoyu Wang, Yan Zheng, and Yang Liu. 2024b. Prompt injection attack against llm-integrated applications. Preprint, arXiv:2306.05499.

<|ref|>text<|/ref|><|det|>[[510, 531, 884, 611]]<|/det|>
Yinqiu Liu, Ruichen Zhang, Haoxiang Luo, Yijing Lin, Geng Sun, Dusit Niyato, Hongyang Du, Zehui Xiong, Yonggang Wen, Abbas Jamalipour, Dong In Kim, and Ping Zhang. 2025b. Secure multi-llm agentic ai and agentification for edge general intelligence by zero-trust: A survey. Preprint, arXiv:2508.19870.

<|ref|>text<|/ref|><|det|>[[510, 618, 884, 697]]<|/det|>
Yupei Liu, Yuqi Jia, Runpeng Geng, Jinyuan Jia, and Neil Zhenqiang Gong. 2024c. Formalizing and benchmarking prompt injection attacks and defenses. In Proceedings of the 33rd USENIX Conference on Security Symposium, SEC '24, USA. USENIX Association.

<|ref|>text<|/ref|><|det|>[[510, 705, 884, 759]]<|/det|>
Zefang Liu. 2025. Autobnb: Multi-agent incident response with large language models. In 2025 13th International Symposium on Digital Forensics and Security (ISDFS), pages 1–6.

<|ref|>text<|/ref|><|det|>[[510, 766, 884, 832]]<|/det|>
Weidi Luo, Shenghong Dai, Xiaogeng Liu, Suman Banerjee, Huan Sun, Muhao Chen, and Chaowei Xiao. 2025. Agrail: A lifelong agent guardrail with effective and adaptive safety detection. Preprint, arXiv:2502.11448.

<|ref|>text<|/ref|><|det|>[[510, 841, 884, 920]]<|/det|>
Phung Duc Luong, Le Tran Gia Bao, Nguyen Vu Khai Tam, Dong Huu Nguyen Khoa, Nguyen Huu Quyen, Van-Hau Pham, and Phan The Duy. 2025. xoffense: An ai-driven autonomous penetration testing framework with offensive knowledge-enhanced llms and multi agent systems. Preprint, arXiv:2509.13021.