<|ref|>text<|/ref|><|det|>[[174, 104, 824, 133]]<|/det|>
Raymond Wong, Michael Lee, Chris Lee, et al. Validation of neuron activation patterns for artificial intelligence models in oculomics. Scientific Reports, 14(1):1–10, 2024.

<|ref|>text<|/ref|><|det|>[[174, 142, 825, 184]]<|/det|>
Chao-Yuan Wu, R Manmatha, Alexander J Smola, and Philipp Krahenbuhl. Sampling matters in deep embedding learning. In Proceedings of the IEEE international conference on computer vision, pp. 2840–2848, 2017.

<|ref|>text<|/ref|><|det|>[[174, 194, 824, 222]]<|/det|>
Han Ye, Tianyu Zhang, Yizhuo Li, Wei Liu, and Li Li. How do vision transformers work? arXiv preprint arXiv:2202.06709, 2022.

<|ref|>text<|/ref|><|det|>[[174, 231, 824, 270]]<|/det|>
Michael Zhang, James Lucas, Jimmy Ba, and Geoffrey Hinton. Lookahead optimizer: k steps forward, 1 step back. In Advances in Neural Information Processing Systems, pp. 9593–9604, 2019.