<|ref|>text<|/ref|><|det|>[[116, 86, 489, 139]]<|/det|>
Ron F. Del Rosario, Klaudia Krawiecka, and Christian Schroeder de Witt. 2025. Architecting resilient llm agents: A guide to secure plan-then-execute implementations. Preprint, arXiv:2509.08646.

<|ref|>text<|/ref|><|det|>[[116, 152, 488, 204]]<|/det|>
Bikash Saha and Sandeep Kumar Shukla. 2025. Malgen: A generative agent framework for modeling malicious software in cybersecurity. Preprint, arXiv:2506.07586.

<|ref|>text<|/ref|><|det|>[[116, 218, 488, 284]]<|/det|>
Shoumik Saha, Jifan Chen, Sam Mayers, Sanjay Krishna Gouda, Zijian Wang, and Varun Kumar. 2025. Breaking the code: Security assessment of ai code agents through systematic jailbreaking attacks. Preprint, arXiv:2510.01359.

<|ref|>text<|/ref|><|det|>[[116, 298, 489, 377]]<|/det|>
Timo Schick, Jane Dwivedi-Yu, Roberto Dessì, Roberta Raileanu, Maria Lomeli, Eric Hambro, Luke Zettlemoyer, Nicola Cancedda, and Thomas Scialom. 2023. Toolformer: Language models can teach themselves to use tools. In Thirty-seventh Conference on Neural Information Processing Systems.

<|ref|>text<|/ref|><|det|>[[117, 390, 489, 483]]<|/det|>
Yuval Schwartz, Lavi Ben-Shimol, Dudu Mimran, Yuval Elovici, and Asaf Shabtai. 2025. Llmcloudhunter: Harnessing llms for automated extraction of detection rules from cloud-based cit. In Proceedings of the ACM on Web Conference 2025, WWW '25, page 1922–1941, New York, NY, USA. Association for Computing Machinery.

<|ref|>text<|/ref|><|det|>[[116, 496, 489, 537]]<|/det|>
Zedian Shao, Hongbin Liu, Jaden Mu, and Neil Zhenqiang Gong. 2024. Enhancing prompt injection attacks to llms via poisoning alignment.

<|ref|>text<|/ref|><|det|>[[116, 549, 488, 602]]<|/det|>
Mohammed A. Shehab. 2025. Agentic-ai healthcare: Multilingual, privacy-first framework with mcp agents. arXiv preprint, arXiv:2510.02325. Preprint, submitted 25 Sep 2025, cs.CR / cs.AI.

<|ref|>text<|/ref|><|det|>[[116, 615, 489, 721]]<|/det|>
Xiangmin Shen, Lingzhi Wang, Zhenyuan Li, Yan Chen, Wencheng Zhao, Dawei Sun, Jiashui Wang, and Wei Ruan. 2025. Pentestagent: Incorporating llm agents to automated penetration testing. In Proceedings of the 20th ACM Asia Conference on Computer and Communications Security, ASIA CCS '25, page 375–391, New York, NY, USA. Association for Computing Machinery.

<|ref|>text<|/ref|><|det|>[[116, 734, 488, 787]]<|/det|>
Tianneng Shi, Jingxuan He, Zhun Wang, Linyu Wu, Hongwei Li, Wenbo Guo, and Dawn Song. 2025. Progent: Programmable privilege control for llm agents.

<|ref|>text<|/ref|><|det|>[[116, 800, 489, 853]]<|/det|>
Noah Shinn, Federico Cassano, Edward Berman, Ashwin Gopinath, Karthik Narasimhan, and Shunyu Yao. 2023. Reflexion: Language agents with verbal reinforcement learning. Preprint, arXiv:2303.11366.

<|ref|>text<|/ref|><|det|>[[116, 866, 489, 919]]<|/det|>
Brian Singer, Keane Lucas, Lakshmi Adiga, Meghna Jain, Lujo Bauer, and Vyas Sekar. 2025. On the feasibility of using llms to autonomously execute multihost network attacks. Preprint, arXiv:2501.16466.

<|ref|>text<|/ref|><|det|>[[510, 86, 885, 152]]<|/det|>
Ronal Singh, Shahroz Tariq, Fatemeh Jalalvand, Mohan Baruwal Chhetri, Surya Nepal, Cecile Paris, and Martin Lochner. 2025. Llms in the soc: An empirical study of human-ai collaboration in security operations centres. Preprint, arXiv:2508.18947.

<|ref|>text<|/ref|><|det|>[[510, 164, 885, 242]]<|/det|>
Joar Skalse, Nikolaus H. R. Howe, Dmitrii Krasheninnikov, and David Krueger. 2022. Defining and characterizing reward hacking. In Proceedings of the 36th International Conference on Neural Information Processing Systems, NIPS '22, Red Hook, NY, USA. Curran Associates Inc.

<|ref|>text<|/ref|><|det|>[[510, 255, 885, 334]]<|/det|>
Shuang Song, Yifei Zhang, and Neng Gao. 2025. Confront insider threat: Precise anomaly detection in behavior logs based on LLM fine-tuning. In Proceedings of the 31st International Conference on Computational Linguistics, pages 8589–8601, Abu Dhabi, UAE. Association for Computational Linguistics.

<|ref|>text<|/ref|><|det|>[[510, 346, 884, 386]]<|/det|>
Izaiah Sun, Daniel Tan, and Andy Deng. 2025. Lisa technical report: An agentic framework for smart contract auditing.

<|ref|>text<|/ref|><|det|>[[510, 398, 885, 490]]<|/det|>
Minxue Tang, Anna Dai, Louis DiValentin, Aolin Ding, Amin Hass, Neil Zhenqiang Gong, Yiran Chen, and Hai "Helen" Li. 2024. ModelGuard: Information-Theoretic defense against model extraction attacks. In 33rd USENIX Security Symposium (USENIX Security 24), pages 5305–5322, Philadelphia, PA. USENIX Association.

<|ref|>text<|/ref|><|det|>[[510, 502, 885, 569]]<|/det|>
Amine Tellache, Abdelaziz Amara Korba, Amdjed Mokhtari, Horea Moldovan, and Yacine Ghamri-Doudane. 2025. Advancing autonomous incident response: Leveraging llms and cyber threat intelligence. Preprint, arXiv:2508.10677.

<|ref|>text<|/ref|><|det|>[[510, 580, 885, 647]]<|/det|>
Yifang Tian, Yaming Liu, Zichun Chong, Zihang Huang, and Hans-Arno Jacobsen. 2025. Gala: Can graph-augmented large language model agentic workflows elevate root cause analysis? Preprint, arXiv:2508.12472.

<|ref|>text<|/ref|><|det|>[[510, 658, 884, 712]]<|/det|>
Dheer Toprani and Vijay K. Madisetti. 2025. Llm agentic workflow for automated vulnerability detection and remediation in infrastructure-as-code. IEEE Access, 13:69175–69181.

<|ref|>text<|/ref|><|det|>[[510, 723, 884, 803]]<|/det|>
Ada Defne Tur, Nicholas Meade, Xing Han Lù, Alejandra Zambrano, Arkil Patel, Esin DURMUS, Spandana Gella, Karolina Stanczak, and Siva Reddy. 2025. Safearena: Evaluating the safety of autonomous web agents. In Forty-second International Conference on Machine Learning.

<|ref|>text<|/ref|><|det|>[[510, 815, 885, 919]]<|/det|>
Meet Udeshi, Minghao Shao, Haoran Xi, Nanda Rani, Kimberly Milner, Venkata Sai Charan Putrevu, Brendan Dolan-Gavitt, Sandeep Kumar Shukla, Prashanth Krishnamurthy, Farshad Khorrami, Ramesh Karri, and Muhammad Shafique. 2025. D-cipher: Dynamic collaborative intelligent multi-agent system with planner and heterogeneous executors for offensive security. Preprint, arXiv:2502.10931.