<|ref|>sub_title<|/ref|><|det|>[[173, 102, 287, 118]]<|/det|>
## REFERENCES

<|ref|>text<|/ref|><|det|>[[173, 126, 822, 155]]<|/det|>
Martin Arjovsky, Léon Bottou, Ishaan Gulrajani, and David Lopez-Paz. Invariant risk minimization. arXiv preprint arXiv:1907.02893, 2019.

<|ref|>text<|/ref|><|det|>[[174, 165, 824, 208]]<|/det|>
David Bau, Bolei Zhou, Aditya Khosla, Aude Oliva, and Antonio Torralba. Network dissection: Quantifying interpretability of deep visual representations. In Proceedings of the IEEE conference on computer vision and pattern recognition, pp. 6541–6549, 2017.

<|ref|>text<|/ref|><|det|>[[174, 217, 825, 259]]<|/det|>
Ting Chen, Simon Kornblith, Mohammad Norouzi, and Geoffrey Hinton. A simple framework for contrastive learning of visual representations. In International conference on machine learning, pp. 1597–1607. PMLR, 2020.

<|ref|>text<|/ref|><|det|>[[174, 269, 824, 298]]<|/det|>
Wentao Cheng and Tong Zhang. Improving deep learning for classification with unknown label noise. In International Conference on Machine Learning, pp. 6059–6081. PMLR, 2023.

<|ref|>text<|/ref|><|det|>[[174, 308, 824, 351]]<|/det|>
Jiankang Deng, Jia Guo, Niannan Xue, and Stefanos Zafeiriou. Arcface: Additive angular margin loss for deep face recognition. In Proceedings of the IEEE/CVF conference on computer vision and pattern recognition, pp. 4690–4699, 2019.

<|ref|>text<|/ref|><|det|>[[174, 360, 825, 417]]<|/det|>
Alexey Dosovitskiy, Lucas Beyer, Alexander Kolesnikov, Dirk Weissenborn, Xiaohua Zhai, Thomas Unterthiner, Mostafa Dehghani, Matthias Minderer, Georg Heigold, Sylvain Gelly, Jakob Uszkoreit, and Neil Houlsby. An image is worth  \( 16 \times 16 \)  words: Transformers for image recognition at scale. In International Conference on Learning Representations, 2021.

<|ref|>text<|/ref|><|det|>[[174, 427, 824, 455]]<|/det|>
Ronald A Fisher. The use of multiple measurements in taxonomic problems. Annals of eugenics, 7(2):179–188, 1936.

<|ref|>text<|/ref|><|det|>[[174, 465, 824, 494]]<|/det|>
Chuan Guo, Geoff Pleiss, Yu Sun, and Kilian Q Weinberger. On calibration of modern neural networks. In International Conference on Machine Learning, pp. 1321–1330. PMLR, 2017.

<|ref|>text<|/ref|><|det|>[[174, 504, 824, 546]]<|/det|>
Raia Hadsell, Sumit Chopra, and Yann LeCun. Dimensionality reduction by learning an invariant mapping. In 2006 IEEE computer society conference on computer vision and pattern recognition (CVPR'06), volume 2, pp. 1735–1742. IEEE, 2006.

<|ref|>text<|/ref|><|det|>[[174, 556, 824, 598]]<|/det|>
Kaiming He, Xiangyu Zhang, Shaoqing Ren, and Jian Sun. Deep residual learning for image recognition. In Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition, pp. 770–778, 2016.

<|ref|>text<|/ref|><|det|>[[174, 608, 825, 651]]<|/det|>
Kaiming He, Haoqi Fan, Yuxin Wu, Saining Xie, and Ross Girshick. Momentum contrast for unsupervised visual representation learning. In Proceedings of the IEEE/CVF conference on computer vision and pattern recognition, pp. 9729–9738, 2020.

<|ref|>text<|/ref|><|det|>[[174, 661, 824, 690]]<|/det|>
Dan Hendrycks and Thomas Dietterich. Benchmarking neural network robustness to common corruptions and perturbations. arXiv preprint arXiv:1903.12261, 2019.

<|ref|>text<|/ref|><|det|>[[174, 700, 824, 728]]<|/det|>
Alexander Hermans, Lucas Beyer, and Bastian Leibe. In defense of the triplet loss for person re-identification. arXiv preprint arXiv:1703.07737, 2017.

<|ref|>text<|/ref|><|det|>[[174, 738, 825, 780]]<|/det|>
Prannay Khosla, Piotr Teterwak, Chen Wang, Aaron Sarna, Yonglong Tian, Phillip Isola, Aaron Maschinot, Ce Liu, and Dilip Krishnan. Supervised contrastive learning. In Advances in Neural Information Processing Systems (NeurIPS), 2020.

<|ref|>text<|/ref|><|det|>[[174, 790, 824, 832]]<|/det|>
Been Kim, Martin Wattenberg, Justin Gilmer, Carrie Cai, James Wexler, Fernanda Viegas, and Rory Sayres. Interpretability beyond feature attribution: Quantitative testing with concept activation vectors (tcav). In International Conference on Machine Learning (ICML), 2018.

<|ref|>text<|/ref|><|det|>[[174, 842, 824, 883]]<|/det|>
Simon Kornblith, Mohammad Norouzi, Honglak Lee, and Geoffrey Hinton. Similarity of neural network representations revisited. In International Conference on Machine Learning (ICML), 2019.

<|ref|>text<|/ref|><|det|>[[174, 895, 822, 923]]<|/det|>
M Kumar, Benjamin Packer, and Daphne Koller. Self-paced learning for latent variable models. Advances in neural information processing systems, 23, 2010.