<|ref|>text<|/ref|><|det|>[[172, 103, 825, 147]]<|/det|>
Parker Molloy. How trump plans to weaponize ai’s “superhuman persuasion”, July 2025. URL https://www.readtpa.com/p/how-trump-plans-to-weaponize-ais. The Present Age (Substack).

<|ref|>text<|/ref|><|det|>[[172, 155, 826, 211]]<|/det|>
Akiko Murakami and Rudy Raymond. Support or oppose? classifying positions in online debates from reply activities and opinion expressions. In Coling 2010: Posters, pages 869–875, Beijing, China, August 2010. Coling 2010 Organizing Committee. URL https://aclanthology.org/C10-2100.

<|ref|>text<|/ref|><|det|>[[172, 220, 824, 249]]<|/det|>
Hannes Mühleisen and Mark Raasveldt. duckdb: DBI Package for the DuckDB Database Management System, 2025. URL https://r.duckdb.org/. R package version 1.3.2.9014.

<|ref|>text<|/ref|><|det|>[[172, 257, 824, 300]]<|/det|>
John Nosta. Ai’s superhuman persuasion, October 2023. URL https://www.psychologytoday.com/us/blog/the-digital-self/202310/ais-superhuman-persuasion.

<|ref|>text<|/ref|><|det|>[[172, 309, 825, 339]]<|/det|>
NSDA. Policy debate judge training guide, 2025. URL https://sites.google.com/view/judge-training/how-to-judge-debate/policy-debate. Accessed 6 Aug 2025.

<|ref|>text<|/ref|><|det|>[[172, 346, 825, 417]]<|/det|>
Matan Orbach, Yonatan Bilu, Assaf Toledo, Dan Lahav, Michal Jacovi, Ranit Aharonov, and Noam Slonim. Out of the echo chamber: Detecting countering debate speeches. In Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics, pages 7073–7086, Online, July 2020. Association for Computational Linguistics. doi: 10.18653/v1/2020.acl-main.633. URL https://aclanthology.org/2020.acl-main.633.

<|ref|>text<|/ref|><|det|>[[172, 425, 825, 469]]<|/det|>
JoonSung Park, Joseph C. O'Brien, Carrie J. Cai, Meredith Ringel Morris, Percy Liang, and Michael S. Bernstein. Generative agents: Interactive simulacra of human behavior. In Proceedings of the 36th Annual ACM Symposium on User Interface Software and Technology, pages 1–22, 2023.

<|ref|>text<|/ref|><|det|>[[172, 476, 825, 547]]<|/det|>
Ruty Rinott, Lena Dankin, Carlos Alzate Perez, Mitesh M. Khapra, Ehud Aharoni, and Noam Slonim. Show me your evidence - an automatic method for context dependent evidence detection. In Proceedings of the 2015 Conference on Empirical Methods in Natural Language Processing, pages 440–450, Lisbon, Portugal, September 2015. Association for Computational Linguistics. doi:10.18653/v1/D15-1050. URL https://aclanthology.org/D15-1050.

<|ref|>text<|/ref|><|det|>[[172, 556, 824, 585]]<|/det|>
Alexander Rogiers, Sander Noels, Maarten Buyl, and Tijl De Bie. Persuasion with large language models: a survey, 2024. URL https://arxiv.org/abs/2411.06837.

<|ref|>text<|/ref|><|det|>[[172, 593, 825, 636]]<|/det|>
Aymeric Roucher, Albert Villanova del Moral, Thomas Wolf, Leandro von Werra, and Erik Kaunismäki. 'smolagents': a smol library to build great agentic systems. https://github.com/huggingface/smolagents, 2025.

<|ref|>text<|/ref|><|det|>[[172, 644, 825, 756]]<|/det|>
Allen Roush, Yusuf Shabazz, Arvind Balaji, Peter Zhang, Stefano Mezza, Markus Zhang, Sanjay Basu, Sriram Vishwanath, Mehdi Fatemi, and Ravid Shwartz Ziv. Opendebateevidence: A massive-scale argument mining and summarization dataset. In A. Globerson, L. Mackey, D. Belgrave, A. Fan, U. Paquet, J. Tomczak, and C. Zhang, editors, Advances in Neural Information Processing Systems, volume 37, pages 34270–34293. Curran Associates, Inc., 2024. URL https://proceedings.neurips.cc/paper_files/paper/2024/file/3c630d28df1cff44314d5798f82e02ec-Paper-Datasets_and_Benchmarks_Track.pdf.

<|ref|>text<|/ref|><|det|>[[172, 764, 825, 807]]<|/det|>
Francesco Salvi, Manoel Horta Ribeiro, Riccardo Gallotti, and Robert West. On the conversational persuasiveness of GPT-4. Nature Human Behaviour, 2025. doi: 10.1038/s41562-025-02194-6. URL https://www.nature.com/articles/s41562-025-02194-6.

<|ref|>text<|/ref|><|det|>[[172, 816, 825, 873]]<|/det|>
Keshav Singh, Naoya Inoue, Farjana Sultana, and Kentaro Inui. Conceptualizing and constructing a lexical resource of sentential arguments. In Proceedings of the Eleventh International Conference on Language Resources and Evaluation (LREC 2018), Miyazaki, Japan, May 2018. European Language Resources Association (ELRA). URL https://aclanthology.org/L18-1037.

<|ref|>text<|/ref|><|det|>[[172, 881, 825, 922]]<|/det|>
Noam Slonim, Yonatan Bilu, Carlos Alzate, Roy Bar-Haim, Shay Bogin, Francesca Bonin, Leshem Choshen, Edo Cohen-Karlik, Eyal Dudin, and Liat Ein-Dor. An autonomous debating system. Nature, 591(7850):379–384, 2021.