<|ref|>text<|/ref|><|det|>[[116, 86, 488, 113]]<|/det|>
Isaac David and Arthur Gervais. 2025. Multi-agent penetration testing ai for the web (mapta).

<|ref|>text<|/ref|><|det|>[[116, 121, 488, 161]]<|/det|>
Christian Schroeder de Witt. 2025. Open challenges in multi-agent security: Towards secure systems of interacting ai agents. Preprint, arXiv:2505.02077.

<|ref|>text<|/ref|><|det|>[[117, 169, 488, 286]]<|/det|>
Lauren Deason, Adam Bali, Ciprian Bejean, Diana Bolocan, James Crnkovich, Ioana Croitoru, Krishna Durai, Chase Midler, Calin Miron, David Molnar, Brad Moon, Bruno Ostarevic, Alberto Peltea, Matt Rosenberg, Catalin Sandu, Arthur Saputkin, Sagar Shah, Daniel Stan, Ernest Szocs, and 4 others. 2025. Cybersoceval: Benchmarking llms capabilities for malware analysis and threat intelligence reasoning. Preprint, arXiv:2509.20166.

<|ref|>text<|/ref|><|det|>[[116, 294, 488, 360]]<|/det|>
Edoardo Debenedetti, Ilia Shumailov, Tianqi Fan, Jamie Hayes, Nicholas Carlini, Daniel Fabian, Christoph Kern, Chongyang Shi, Andreas Terzis, and Florian Tramèr. 2025. Defeating prompt injections by design. Preprint, arXiv:2503.18813.

<|ref|>text<|/ref|><|det|>[[116, 368, 488, 460]]<|/det|>
Edoardo Debenedetti, Jie Zhang, Mislav Balunovic, Luca Beurer-Kellner, Marc Fischer, and Florian Tramèr. 2024. Agentdojo: A dynamic environment to evaluate prompt injection attacks and defenses for LLM agents. In The Thirty-eight Conference on Neural Information Processing Systems Datasets and Benchmarks Track.

<|ref|>text<|/ref|><|det|>[[116, 467, 488, 560]]<|/det|>
Gelei Deng, Yi Liu, Víctor Mayoral-Vilches, Peng Liu, Yuekang Li, Yuan Xu, Tianwei Zhang, Yang Liu, Martin Pinzger, and Stefan Rass. 2024a. PentestGPT: Evaluating and harnessing large language models for automated penetration testing. In 33rd USENIX Security Symposium (USENIX Security 24), pages 847–864, Philadelphia, PA. USENIX Association.

<|ref|>text<|/ref|><|det|>[[117, 568, 489, 673]]<|/det|>
Yinlin Deng, Chunqiu Steven Xia, Haoran Peng, Chenyuan Yang, and Lingming Zhang. 2023. Large language models are zero-shot fuzzers: Fuzzing deep-learning libraries via large language models. In Proceedings of the 32nd ACM SIGSOFT International Symposium on Software Testing and Analysis, ISSTA 2023, page 423–435, New York, NY, USA. Association for Computing Machinery.

<|ref|>text<|/ref|><|det|>[[117, 680, 488, 786]]<|/det|>
Yinlin Deng, Chunqiu Steven Xia, Chenyuan Yang, Shizhuo Dylan Zhang, Shujing Yang, and Lingming Zhang. 2024b. Large language models are edge-case generators: Crafting unusual programs for fuzzing deep learning libraries. In Proceedings of the IEEE/ACM 46th International Conference on Software Engineering, ICSE '24, New York, NY, USA. Association for Computing Machinery.

<|ref|>text<|/ref|><|det|>[[116, 793, 488, 858]]<|/det|>
Zehang Deng, Yongjian Guo, Changzhou Han, Wan-lun Ma, Junwu Xiong, Sheng Wen, and Yang Xiang. 2024c. Ai agents under threat: A survey of key security challenges and future pathways. Preprint, arXiv:2406.02630.

<|ref|>text<|/ref|><|det|>[[117, 866, 488, 920]]<|/det|>
Fatih Deniz, Dorde Popovic, Yazan Boshmaf, Euisuh Jeong, Minhaj Ahmad, Sanjay Chawla, and Issa Khalil. 2025. aixamine: Simplified llm safety and security. Preprint, arXiv:2504.14985.

<|ref|>text<|/ref|><|det|>[[511, 86, 884, 139]]<|/det|>
Alaeddine Diaf, Abdelaziz Amara Korba, Nour Elislem Karabadji, and Yacine Ghamri-Doudane. 2025. Bart-predict: Empowering iot security with llm-driven cyber threat prediction.

<|ref|>text<|/ref|><|det|>[[510, 147, 884, 226]]<|/det|>
Shen Dong, Shaochen Xu, Pengfei He, Yige Li, Jiliang Tang, Tianming Liu, Hui Liu, and Zhen Xiang. 2025a. Memory injection attacks on LLM agents via query-only interaction. In The Thirty-ninth Annual Conference on Neural Information Processing Systems.

<|ref|>text<|/ref|><|det|>[[510, 235, 884, 288]]<|/det|>
Shen Dong, Shaochen Xu, Pengfei He, Yige Li, Jiliang Tang, Tianming Liu, Hui Liu, and Zhen Xiang. 2025b. A practical memory injection attack against llm agents. Preprint, arXiv:2503.03704.

<|ref|>text<|/ref|><|det|>[[510, 296, 884, 363]]<|/det|>
Mohamad Fakih, Rahul Dharmaji, Halima Bouzidi, Gustavo Quiros Araya, Oluwatosin Ogundare, and Mohammad Abdullah Al Faruque. 2025. Llm4cve: Enabling iterative automated vulnerability repair with large language models. Preprint, arXiv:2501.03446.

<|ref|>text<|/ref|><|det|>[[510, 371, 884, 411]]<|/det|>
Richard Fang, Rohan Bindu, Akul Gupta, and Daniel Kang. 2024. Llm agents can autonomously exploit one-day vulnerabilities. Preprint, arXiv:2404.08144.

<|ref|>text<|/ref|><|det|>[[510, 419, 884, 485]]<|/det|>
Neil Fendley, Edward W. Staley, Joshua Carney, William Redman, Marie Chau, and Nathan Drenkow. 2025. A systematic review of poisoning attacks against large language models. Preprint, arXiv:2506.06518.

<|ref|>text<|/ref|><|det|>[[510, 494, 884, 547]]<|/det|>
Jiayi Fu, Xuandong Zhao, Chengyuan Yao, Heng Wang, Qi Han, and Yanghua Xiao. 2025a. Reward shaping to mitigate reward hacking in rlhf. Preprint, arXiv:2502.18770.

<|ref|>text<|/ref|><|det|>[[510, 555, 884, 622]]<|/det|>
Tingchen Fu, Mrinank Sharma, Philip Torr, Shay B Cohen, David Krueger, and Fazl Barez. 2025b. Poisonbench: Assessing large language model vulnerability to poisoned preference data. In Forty-second International Conference on Machine Learning.

<|ref|>text<|/ref|><|det|>[[510, 630, 884, 683]]<|/det|>
Yuchuan Fu, Xiaohan Yuan, and Dongxia Wang. 2025c. Ras-eval: A comprehensive benchmark for security evaluation of llm agents in real-world environments. Preprint, arXiv:2506.15253.

<|ref|>text<|/ref|><|det|>[[510, 692, 884, 757]]<|/det|>
Stefano Fumero, Kai Huang, Matteo Boffa, Danilo Giordano, Marco Mellia, Zied Ben Houidi, and Dario Rossi. 2025. Cybersleuth: Autonomous blue-team llm agent for web attack forensics. Preprint, arXiv:2508.20643.

<|ref|>text<|/ref|><|det|>[[510, 766, 884, 844]]<|/det|>
Yuyou Gan, Yong Yang, Zhe Ma, Ping He, Rui Zeng, Yiming Wang, Qingming Li, Chunyi Zhou, Songze Li, Ting Wang, Yunjun Gao, Yingcai Wu, and Shouling Ji. 2024. Navigating the risks: A survey of security, privacy, and ethics threats in llm-based agents. Preprint, arXiv:2411.09523.

<|ref|>text<|/ref|><|det|>[[510, 854, 884, 919]]<|/det|>
Suyu Ge, Chunting Zhou, Rui Hou, Madian Khabsa, Yi-Chia Wang, Qifan Wang, Jiawei Han, and Yuning Mao. 2023. Mart: Improving llm safety with multi-round automatic red-teaming. Preprint, arXiv:2311.07689.