<|ref|>text<|/ref|><|det|>[[116, 86, 489, 151]]<|/det|>
Luca Gioacchini, Marco Mellia, Idilio Drago, Alexander Delsanto, Giuseppe Siracusano, and Roberto Bifulco. 2024. Autopenbench: Benchmarking generative agents for penetration testing. Preprint, arXiv:2410.03225.

<|ref|>text<|/ref|><|det|>[[117, 165, 489, 270]]<|/det|>
Kai Greshake, Sahar Abdelnabi, Shailesh Mishra, Christoph Endres, Thorsten Holz, and Mario Fritz. 2023. Not what you’ve signed up for: Compromising real-world llm-integrated applications with indirect prompt injection. In Proceedings of the 16th ACM Workshop on Artificial Intelligence and Security, AISec ’23, page 79–90, New York, NY, USA. Association for Computing Machinery.

<|ref|>text<|/ref|><|det|>[[116, 283, 488, 349]]<|/det|>
Jinyao Guo, Chengpeng Wang, Xiangzhe Xu, Zian Su, and Xiangyu Zhang. 2025a. Repoaudit: An autonomous LLM-agent for repository-level code auditing. In Forty-second International Conference on Machine Learning.

<|ref|>text<|/ref|><|det|>[[116, 362, 488, 415]]<|/det|>
Qiming Guo, Jinwen Tang, and Xingran Huang. 2025b. Attacking llms and ai agents: Advertisement embedding attacks against large language models. Preprint, arXiv:2508.17674.

<|ref|>text<|/ref|><|det|>[[116, 429, 488, 481]]<|/det|>
Shanshan Han, Qifan Zhang, Yuhang Yao, Weizhao Jin, and Zhaozhuo Xu. 2025. Llm multi-agent systems: Challenges and open problems. Preprint, arXiv:2402.03578.

<|ref|>text<|/ref|><|det|>[[116, 495, 488, 549]]<|/det|>
Andreas Happe and Jürgen Cito. 2025a. Can llms hack enterprise networks? autonomous assumed breach penetration-testing active directory networks. ACM Trans. Softw. Eng. Methodol. Just Accepted.

<|ref|>text<|/ref|><|det|>[[116, 561, 488, 601]]<|/det|>
Andreas Happe and Jürgen Cito. 2025b. On the surprising efficacy of llms for penetration-testing. Preprint, arXiv:2507.00829.

<|ref|>text<|/ref|><|det|>[[116, 614, 489, 694]]<|/det|>
Pengfei He, Yuping Lin, Shen Dong, Han Xu, Yue Xing, and Hui Liu. 2025a. Red-teaming LLM multi-agent systems via communication attacks. In Findings of the Association for Computational Linguistics: ACL 2025, pages 6726–6747, Vienna, Austria. Association for Computational Linguistics.

<|ref|>text<|/ref|><|det|>[[116, 706, 488, 747]]<|/det|>
Xu He, Di Wu, Yan Zhai, and Kun Sun. 2025b. Sentinelagent: Graph-based anomaly detection in multi-agent systems. Preprint, arXiv:2505.24201.

<|ref|>text<|/ref|><|det|>[[116, 760, 488, 800]]<|/det|>
Yifeng He, Ethan Wang, Yuyang Rong, Zifei Cheng, and Hao Chen. 2024. Security of ai agents. Preprint, arXiv:2406.08689.

<|ref|>text<|/ref|><|det|>[[116, 813, 488, 854]]<|/det|>
Julius Henke. 2025. Autopentest: Enhancing vulnerability management with autonomous llm agents. Preprint, arXiv:2505.10321.

<|ref|>text<|/ref|><|det|>[[116, 866, 488, 920]]<|/det|>
Jinwei HU, Yi DONG, Zhengtao DING, and Xiaowei HUANG. 2025. Enhancing robustness of llm-driven multi-agent systems through randomized smoothing. Chinese Journal of Aeronautics, page 103779.

<|ref|>text<|/ref|><|det|>[[511, 86, 883, 179]]<|/det|>
Xueyu Hu, Tao Xiong, Biao Yi, Zishu Wei, Ruixuan Xiao, Yurun Chen, Jiasheng Ye, Meiling Tao, Xiangxin Zhou, Ziyu Zhao, Yuhuai Li, Shengze Xu, Shenzhi Wang, Xinchen Xu, Shuofei Qiao, Zhaokai Wang, Kun Kuang, Tieyong Zeng, Liang Wang, and 10 others. 2025. Os agents: A survey on mllm-based agents for computer, phone and browser use.

<|ref|>text<|/ref|><|det|>[[510, 187, 883, 241]]<|/det|>
Isamu Isozaki, Manil Shrestha, Rick Console, and Edward Kim. 2024. Towards automated penetration testing: Introducing llm benchmark, analysis, and improvements. Preprint, arXiv:2410.17141.

<|ref|>text<|/ref|><|det|>[[510, 250, 884, 343]]<|/det|>
Feiran Jia, Tong Wu, Xin Qin, and Anna Squicciarini. 2025. The task shield: Enforcing task alignment to defend against indirect prompt injection in LLM agents. In Proceedings of the 63rd Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers), pages 29680–29697, Vienna, Austria. Association for Computational Linguistics.

<|ref|>text<|/ref|><|det|>[[510, 352, 883, 391]]<|/det|>
Yongrae Jo and Chanik Park. 2025. Byzantine-robust decentralized coordination of llm agents. Preprint, arXiv:2507.14928.

<|ref|>text<|/ref|><|det|>[[510, 401, 884, 442]]<|/det|>
Mintong Kang and Bo Li. 2024.  \( r^{2} \) -guard: Robust reasoning enabled llm guardrail via knowledge-enhanced logical reasoning.

<|ref|>text<|/ref|><|det|>[[510, 451, 883, 491]]<|/det|>
Jan Keller and Jan Nowakowski. 2024. Ai-powered patching: the future of automated vulnerability fixes. Technical report.

<|ref|>text<|/ref|><|det|>[[510, 501, 883, 529]]<|/det|>
Jun Kevin and Pujianto Yugopuspito. 2025. Smartllm: Smart contract auditing using custom generative ai.

<|ref|>text<|/ref|><|det|>[[510, 537, 883, 578]]<|/det|>
Juhee Kim, Woohyuk Choi, and Byoungyoung Lee. 2025. Prompt flow integrity to prevent privilege escalation in llm agents.

<|ref|>text<|/ref|><|det|>[[510, 587, 884, 653]]<|/det|>
Ronny Ko, Jiseong Jeong, Shuyuan Zheng, Chuan Xiao, Tae-Wan Kim, Makoto Onizuka, and Won-Yong Shin. 2025. Seven security challenges that must be solved in cross-domain multi-agent llm systems. Preprint, arXiv:2505.23847.

<|ref|>text<|/ref|><|det|>[[510, 663, 884, 768]]<|/det|>
Dezhang Kong, Shi Lin, Zhenhua Xu, Zhebo Wang, Minghao Li, Yufeng Li, Yilun Zhang, Hujin Peng, Zeyang Sha, Yuyuan Li, Changting Lin, Xun Wang, Xuan Liu, Ningyu Zhang, Chaochao Chen, Muhammad Khurram Khan, and Meng Han. 2025a. A survey of llm-driven ai agent communication: Protocols, security risks, and defense countermeasures. Preprint, arXiv:2506.19676.

<|ref|>text<|/ref|><|det|>[[510, 778, 882, 831]]<|/det|>
He Kong, Die Hu, Jingguo Ge, Liangxiong Li, Tong Li, and Bingzhen Wu. 2025b. Vulnbot: Autonomous penetration testing for a multi-agent collaborative framework. Preprint, arXiv:2501.13411.

<|ref|>text<|/ref|><|det|>[[510, 841, 884, 920]]<|/det|>
Panagiotis Kouvaros, Alessio Lomuscio, Edoardo Pirovano, and Hashan Punchihewa. 2019. Formal verification of open multi-agent systems. In Proceedings of the 18th International Conference on Autonomous Agents and MultiAgent Systems, AAMAS '19, page 179–187, Richland, SC. International